# Generated by Django 4.2.20 on 2025-05-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
